spring:
  application:
    name: ticket-microservice-dataset

# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

# HTTP Server (Tomcat) Port
server: 
  port: 8098
  
management:
  endpoints:
    web:
      exposure:
        include: health,info,hystrix.stream  

